name: Cypress Tests

on:
  push:
    branches:
      - master

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: TsykalanovDima/Test_for...
          ref: master
          token: ${{ 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 }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      # ... остальные шаги ...
